### PR TITLE
Add assigned roles to access token

### PR DESCRIPTION
**Pull request by kulmann**

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/middleware/account_uuid.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-proxy/pullRequest?prid=6082025&bid=19911119)

**Review by butonic — APPROVED** [review]
make the linter happy. good for now.

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/middleware/account_uuid.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-proxy/pullRequest?prid=6082025&bid=19911119)

**Review by IljaN — APPROVED** [review]

**Comment by kulmann** [comment]
Account_uuid middleware tests need mocking from ocis-settings. Will build that in a PR on ocis-settings. After it's merged we can continue here with fixing the account_uuid tests. Until then this PR is blocked.

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/middleware/account_uuid.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-proxy/pullRequest?prid=6082025&bid=19911119)

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/middleware/account_uuid.go  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-proxy/pullRequest?prid=6082025&bid=19911119)

**Pull request merged**
