### PR TITLE
[WIP] Roles Middleware

### PR DESCRIPTION
**Pull request by refs**
# Disclaimer

It contains a lot of local replaces that I decided to push in order to have something reviewable faster.

### `reva`

apply this patch:

```diff
diff --git a/pkg/token/manager/jwt/jwt.go b/pkg/token/manager/jwt/jwt.go
index c92b8ff..bfa28ad 100644
--- a/pkg/token/manager/jwt/jwt.go
+++ b/pkg/token/manager/jwt/jwt.go
@@ -80,9 +80,13 @@ type manager struct {
 // claims are custom claims for the JWT token.
 type claims struct {
        jwt.StandardClaims
-       User *user.User `json:"user"`
+       User  *user.User `json:"user"`
+       Roles []string   `json:"roles,omitempty"`
 }

+// RolesKey refers to roles on a context.Context.
+type RolesKey struct{}
+
 // TODO(labkode): resulting JSON contains internal protobuf fields:
 //  "Username": "einstein",
 //  "XXX_NoUnkeyedLiteral": {},
@@ -101,6 +105,13 @@ func (m *manager) MintToken(ctx context.Context, u *user.User) (string, error) {
                User: u,
        }

+       if ctx.Value(RolesKey{}) != nil {
+               roles := ctx.Value(RolesKey{}).([]string)
+               if len(roles) > 0 {
+                       claims.Roles = roles
+               }
+       }
+
        t := jwt.NewWithClaims(jwt.GetSigningMethod("HS256"), claims)

        tkn, err := t.SignedString([]byte(m.conf.Secret))
```

### `ocis-settings`

Branch: 
Commit (at the moment of this writing): [81b5682](https://github.com/owncloud/ocis-settings/pull/35/commits/81b5682af8a9d310ce28fac89bc36650d8dd5a9b)

## Replaces on `ocis`

```golang
replace github.com/owncloud/ocis-proxy => ../ocis-proxy // this PR
replace github.com/owncloud/ocis-accounts => ../ocis-accounts // checked out on https://github.com/owncloud/ocis-accounts/pull/54
replace github.com/owncloud/ocis-settings => ../ocis-settings // [81b5682](https://github.com/owncloud/ocis-settings/pull/35/commits/81b5682af8a9d310ce28fac89bc36650d8dd5a9b)
replace github.com/cs3org/reva => ../../refs/reva // see patch above
replace github.com/owncloud/ocis-reva => ../ocis-reva // ocis-reva local replace to reva diff (see above)
```

### CODE REVIEW

**Comment by ownclouders** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- pkg/middleware/token/token.go  3
         

Complexity decreasing per file
==============================
+ pkg/middleware/account_uuid.go  -1
         

Clones added
============
- pkg/middleware/create_home.go  1
- pkg/middleware/account_uuid.go  1
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/owncloud/ocis-proxy/pullRequest?prid=5843332&bid=19131721)

**Comment by kulmann** [comment]
Middleware works for global roles - that is cool and a good start, since we will start with globally defined roles.

However, there is e.g. the use case of a role for a specific resource. Example:
```
micro call com.owncloud.api.settings RoleService.AssignRoleToUser '{"assignment": {"accountUuid": "4c510ada-c86b-4815-8820-42cdf82c3d51", "role": "group-admin", "resource": {"type": 5, "id": "abc-123-äöü"}}}'
```
```
micro call com.owncloud.api.settings RoleService.AssignRoleToUser '{"assignment": {"accountUuid": "4c510ada-c86b-4815-8820-42cdf82c3d51", "role": "group-admin", "resource": {"type": 5, "id": "xyz-987-ßßß"}}}'
```
That would be a group admin role for a specific group. Since we are addressing roles by names and don't check for uniqueness so far, this would result in possible name clashes. You would not be able to identify which of the `group-admin` roles the user has, when only minting the group names into the token.

Option 1: We stick with this role name + resource as compound unique identifier. In that case the roles in the token must include the resource.
Option 2: We keep the middleware like it is. In that case we need to ensure uniqueness on role names. We could use UUIDs - that would work, but that would a) complicate composition of roles through code (because you would need to know the uuid of a role when you want to e.g. add a permission to it) and b) would require to work with e.g. bleve for finding the roles within the FS on the settings service.

**Comment by kulmann** [comment]
Since we decided today, that we want to reference everything in settings by uuid, roles will be identified by uuids as well. So the approach this PR took is perfectly fine. Roles for a user will be an array of role-uuids, so string array in the token is perfect.

**Comment by kulmann** [comment]
@IljaN do you know the status on this? would be good to be able to use it for roles & permissions now. If not feasible, I will take a different approach.

**Comment by kulmann** [comment]
Doing a similar thing now in https://github.com/owncloud/ocis-proxy/pull/93

**Comment by refs** [comment]
@kulmann  could we close this in favor of https://github.com/owncloud/ocis-proxy/pull/93 ?

**Comment by refs** [comment]
oh, I just read the changelog, the logic is unrelated to 93

**Comment by kulmann** [comment]
We can close it. It solves the same issue, but without a dedicated field for the roleIDs. We have https://github.com/owncloud/product/issues/177 to track introducing our own struct for the token data.

**Pull request closed without merging**
