### PR TITLE
Point /data to reva frontend

### PR DESCRIPTION
**Pull request by kulmann**
Changes based on owncloud/ocis-proxy#44 (comment)
Part of https://github.com/owncloud/product/issues/72

### CODE REVIEW

**Comment by kulmann** [comment]
Needs https://github.com/owncloud/ocis-reva/pull/261

**Comment by kulmann** [comment]
@micbar codacy complains with `config/proxy-example.json is often changed in this repository` and `config/proxy-example-migration.json is often changed in this repository`. 🙄  Any chance we can disable that check? Because it's only natural that the example config changes...

**Comment by micbar** [comment]
exclude the config folder in codacy.yml

**Review by butonic — APPROVED** [review]

**Comment by PVince81** [comment]
Blocked by https://github.com/owncloud/ocis-proxy/issues/59

**Pull request merged**
